language: python
notifications:
  email: false
sudo: false
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - coverage run manage.py test
after_success:
  - codecov
